"""initial_schema

Revision ID: 2fd6efcfd6c9
Revises: 
Create Date: 2026-05-10 11:25:21.682763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fd6efcfd6c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('VIEWER', 'OPERATOR', 'MANAGER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('connector_instance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('connector_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVO', 'INACTIVO', name='connector_status'), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connector_org_status', 'connector_instance', ['organization_id', 'status'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_table('user_membership',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'OPERATOR', 'MANAGER', 'ADMIN', name='membership_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id')
    )
    op.create_table('verification_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_table('release',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('BORRADOR', 'PENDIENTE', 'EN_VERIFICACION', 'VALIDA', 'CON_ADVERTENCIAS', 'NO_VALIDA', 'ARCHIVADA', name='release_status'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['verification_profile.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version')
    )
    op.create_table('verification_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('connector_instance_id', sa.UUID(), nullable=True),
    sa.Column('rule_template', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.Enum('OBLIGATORIA', 'RECOMENDADA', 'INFORMATIVA', name='severity_type'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_instance_id'], ['connector_instance.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['verification_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_rule_profile_id', 'verification_rule', ['profile_id'], unique=False)
    op.create_table('artifact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('connector_instance_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_instance_id'], ['connector_instance.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifact_release_id', 'artifact', ['release_id'], unique=False)
    op.create_index('ix_artifact_type', 'artifact', ['artifact_type'], unique=False)
    op.create_table('verification_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('VALIDO', 'CON_ADVERTENCIAS', 'NO_VALIDO', name='verdict_type'), nullable=False),
    sa.Column('rule_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_result_executed_at', 'verification_result', ['executed_at'], unique=False)
    op.create_index('ix_verification_result_release_id', 'verification_result', ['release_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_result_release_id', table_name='verification_result')
    op.drop_index('ix_verification_result_executed_at', table_name='verification_result')
    op.drop_table('verification_result')
    op.drop_index('ix_artifact_type', table_name='artifact')
    op.drop_index('ix_artifact_release_id', table_name='artifact')
    op.drop_table('artifact')
    op.drop_index('ix_verification_rule_profile_id', table_name='verification_rule')
    op.drop_table('verification_rule')
    op.drop_table('release')
    op.drop_table('verification_profile')
    op.drop_table('user_membership')
    op.drop_table('project')
    op.drop_index('ix_connector_org_status', table_name='connector_instance')
    op.drop_table('connector_instance')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('organization')
    # ### end Alembic commands ###
