// This file is auto-generated by @hey-api/openapi-ts

import type { Config } from './types.gen';

export type ServerSentEventsOptions<TData = unknown> = Omit<RequestInit, 'method'> &
  Pick<Config, 'method' | 'responseTransformer' | 'responseValidator'> & {
    /**
     * Fetch API implementation. You can use this option to provide a custom
     * fetch instance.
     *
     * @default globalThis.fetch
     */
    fetch?: typeof fetch;
    /**
     * Implementing clients can call request interceptors inside this hook.
     */
    onRequest?: (url: string, init: RequestInit) => Promise<Request>;
    /**
     * Callback invoked when a network or parsing error occurs during streaming.
     *
     * This option applies only if the endpoint returns a stream of events.
     *
     * @param error The error that occurred.
     */
    onSseError?: (error: unknown) => void;
    /**
     * Callback invoked when an event is streamed from the server.
     *
     * This option applies only if the endpoint returns a stream of events.
     *
     * @param event Event streamed from the server.
     * @returns Nothing (void).
     */
    onSseEvent?: (event: StreamEvent<TData>) => void;
    serializedBody?: RequestInit['body'];
    /**
     * Default retry delay in milliseconds.
     *
     * This option applies only if the endpoint returns a stream of events.
     *
     * @default 3000
     */
    sseDefaultRetryDelay?: number;
    /**
     * Maximum number of retry attempts before giving up.
     */
    sseMaxRetryAttempts?: number;
    /**
     * Maximum retry delay in milliseconds.
     *
     * Applies only when exponential backoff is used.
     *
     * This option applies only if the endpoint returns a stream of events.
     *
     * @default 30000
     */
    sseMaxRetryDelay?: number;
    /**
     * Optional sleep function for retry backoff.
     *
     * Defaults to using `setTimeout`.
     */
    sseSleepFn?: (ms: number) => Promise<void>;
    url: string;
  };

export interface StreamEvent<TData = unknown> {
  data: TData extends Record<string, unknown> ? TData[keyof TData] : TData;
  event?: string;
  id?: string;
  retry?: number;
}

export type ServerSentEventsResult<TData = unknown, TReturn = void, TNext = unknown> = {
  stream: AsyncGenerator<
    TData extends Record<string, unknown> ? TData[keyof TData] : TData,
    TReturn,
    TNext
  >;
};

const prepareHeaders = (options: Omit<ServerSentEventsOptions, 'url'>, lastEventId?: string): Headers => {
  const headers = options.headers instanceof Headers
    ? options.headers
    : new Headers(options.headers);
  if (lastEventId !== undefined) {
    headers.set('Last-Event-ID', lastEventId);
  }
  return headers;
};

const fetchSseResponse = async (
  url: string,
  options: Omit<ServerSentEventsOptions, 'url'>,
  headers: Headers,
  signal: AbortSignal,
  onRequest?: ServerSentEventsOptions['onRequest'],
): Promise<Response> => {
  const requestInit: RequestInit = {
    redirect: 'follow',
    ...options,
    body: options.serializedBody,
    headers,
    signal,
  };
  let request = new Request(url, requestInit);
  if (onRequest) {
    request = await onRequest(url, requestInit);
  }
  // fetch must be assigned here, otherwise it would throw the error:
  // TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
  const _fetch = options.fetch ?? globalThis.fetch;
  const response = await _fetch(request);

  if (!response.ok) {
    throw new Error(`SSE failed: ${response.status} ${response.statusText}`);
  }
  if (!response.body) {
    throw new Error('No body in SSE response');
  }
  return response;
};

interface SseParseResult {
  dataLines: string[];
  eventName?: string;
  lastEventId?: string;
  retryDelay?: number;
}

const parseSseChunk = (chunk: string): SseParseResult => {
  const dataLines: string[] = [];
  let eventName: string | undefined;
  let lastEventId: string | undefined;
  let retryDelay: number | undefined;

  for (const line of chunk.split('\n')) {
    if (line.startsWith('data:')) {
      dataLines.push(line.replace(/^data:\s*/, ''));
    } else if (line.startsWith('event:')) {
      eventName = line.replace(/^event:\s*/, '');
    } else if (line.startsWith('id:')) {
      lastEventId = line.replace(/^id:\s*/, '');
    } else if (line.startsWith('retry:')) {
      const parsed = Number.parseInt(line.replace(/^retry:\s*/, ''), 10);
      if (!Number.isNaN(parsed)) {
        retryDelay = parsed;
      }
    }
  }

  return { dataLines, eventName, lastEventId, retryDelay };
};

const processChunkData = async (
  dataLines: string[],
  responseValidator?: ServerSentEventsOptions['responseValidator'],
  responseTransformer?: ServerSentEventsOptions['responseTransformer'],
): Promise<{ data: unknown; hasData: boolean }> => {
  let data: unknown;
  let parsedJson = false;

  if (dataLines.length) {
    const rawData = dataLines.join('\n');
    try {
      data = JSON.parse(rawData);
      parsedJson = true;
    } catch {
      data = rawData;
    }
  }

  if (parsedJson) {
    if (responseValidator) {
      await responseValidator(data);
    }
    if (responseTransformer) {
      data = await responseTransformer(data);
    }
  }

  return { data, hasData: dataLines.length > 0 };
};

const computeBackoff = (
  retryDelay: number,
  attempt: number,
  sseMaxRetryDelay?: number,
): number => {
  return Math.min(retryDelay * 2 ** (attempt - 1), sseMaxRetryDelay ?? 30000);
};

interface StreamContext {
  lastEventId?: string;
  retryDelay: number;
}

const readStreamEvents = async function* <TData,>(
  reader: ReadableStreamDefaultReader<string>,
  ctx: StreamContext,
  onSseEvent: ServerSentEventsOptions<TData>['onSseEvent'],
  responseValidator?: ServerSentEventsOptions<TData>['responseValidator'],
  responseTransformer?: ServerSentEventsOptions<TData>['responseTransformer'],
): AsyncGenerator<TData extends Record<string, unknown> ? TData[keyof TData] : TData, void, unknown> {
  let buffer = '';
  while (true) {
    const { done, value } = await reader.read();
    if (done) return;

    buffer += value;
    buffer = buffer.replace(/\r\n?/g, '\n');
    const chunks = buffer.split('\n\n');
    buffer = chunks.pop() ?? '';

    for (const chunk of chunks) {
      const parsed = parseSseChunk(chunk);
      if (parsed.lastEventId !== undefined) ctx.lastEventId = parsed.lastEventId;
      if (parsed.retryDelay !== undefined) ctx.retryDelay = parsed.retryDelay;

      const { data, hasData } = await processChunkData(
        parsed.dataLines, responseValidator, responseTransformer,
      );

      // Cast data to the expected generic event data type to satisfy TypeScript
      onSseEvent?.({ data: data as TData extends Record<string, unknown> ? TData[keyof TData] : TData, event: parsed.eventName, id: ctx.lastEventId, retry: ctx.retryDelay });

      if (hasData) {
        yield data as TData extends Record<string, unknown> ? TData[keyof TData] : TData;
      }
    }
  }
};

export function createSseClient<TData = unknown>({
  onRequest,
  onSseError,
  onSseEvent,
  responseTransformer,
  responseValidator,
  sseDefaultRetryDelay,
  sseMaxRetryAttempts,
  sseMaxRetryDelay,
  sseSleepFn,
  url,
  ...options
}: ServerSentEventsOptions<TData>): ServerSentEventsResult<TData> {
  const ctx: StreamContext = {
    lastEventId: undefined,
    retryDelay: sseDefaultRetryDelay ?? 3000,
  };

  const sleep = sseSleepFn ?? ((ms: number) => new Promise((resolve) => setTimeout(resolve, ms)));

  const createStream = async function* (): AsyncGenerator<TData extends Record<string, unknown> ? TData[keyof TData] : TData, void, unknown> {
    let attempt = 0;
    const signal = options.signal ?? new AbortController().signal;

    while (true) {
      if (signal.aborted) break;

      attempt++;

      const headers = prepareHeaders(options, ctx.lastEventId);

      try {
        const response = await fetchSseResponse(url, options, headers, signal, onRequest);
        const reader = response.body!.pipeThrough(new TextDecoderStream()).getReader();
        const abortHandler = () => {
          void reader.cancel().catch(() => {});
        };

        signal.addEventListener('abort', abortHandler);

        try {
          yield* readStreamEvents(reader, ctx, onSseEvent, responseValidator, responseTransformer);
          break;
        } finally {
          signal.removeEventListener('abort', abortHandler);
          reader.releaseLock();
        }
      } catch (error) {
        onSseError?.(error);

        if (sseMaxRetryAttempts !== undefined && attempt >= sseMaxRetryAttempts) {
          break;
        }

        const backoff = computeBackoff(ctx.retryDelay, attempt, sseMaxRetryDelay);
        await sleep(backoff);
      }
    }
  };

  const stream = createStream();

  return { stream };
}
