// This file is auto-generated by @hey-api/openapi-ts

import type { BodySerializer, QuerySerializer } from './bodySerializer.gen';
import {
  serializeArrayParam,
  serializeObjectParam,
  serializePrimitiveParam,
} from './pathSerializer.gen';

export interface PathSerializer {
  path: Record<string, unknown>;
  url: string;
}

export const PATH_PARAM_RE = /\{[^{}]+\}/g;

interface PathParamMeta {
  explode: boolean;
  name: string;
  style: 'simple' | 'label' | 'matrix';
}

const parsePathParamMeta = (match: string): PathParamMeta => {
  let explode = false;
  let name = match.substring(1, match.length - 1);
  let style: PathParamMeta['style'] = 'simple';

  if (name.endsWith('*')) {
    explode = true;
    name = name.substring(0, name.length - 1);
  }

  if (name.startsWith('.')) {
    name = name.substring(1);
    style = 'label';
  } else if (name.startsWith(';')) {
    name = name.substring(1);
    style = 'matrix';
  }

  return { explode, name, style };
};

const serializePathParamValue = (
  match: string,
  meta: PathParamMeta,
  value: unknown,
): string => {
  const { explode, name, style } = meta;

  if (Array.isArray(value)) {
    return serializeArrayParam({ explode, name, style, value });
  }

  if (typeof value === 'object') {
    return serializeObjectParam({
      explode,
      name,
      style,
      value: value as Record<string, unknown>,
      valueOnly: true,
    });
  }

  if (style === 'matrix') {
    return `;${serializePrimitiveParam({ name, value: value as string })}`;
  }

  return encodeURIComponent(
    style === 'label' ? `.${value as string}` : (value as string),
  );
};

export const defaultPathSerializer = ({ path, url: _url }: PathSerializer) => {
  let url = _url;
  const matches = _url.match(PATH_PARAM_RE);
  if (matches) {
    for (const match of matches) {
      const meta = parsePathParamMeta(match);
      const value = path[meta.name];

      if (value === undefined || value === null) {
        continue;
      }

      url = url.replace(match, serializePathParamValue(match, meta, value));
    }
  }
  return url;
};

export const getUrl = ({
  baseUrl,
  path,
  query,
  querySerializer,
  url: _url,
}: {
  baseUrl?: string;
  path?: Record<string, unknown>;
  query?: Record<string, unknown>;
  querySerializer: QuerySerializer;
  url: string;
}) => {
  const pathUrl = _url.startsWith('/') ? _url : `/${_url}`;
  let url = (baseUrl ?? '') + pathUrl;
  if (path) {
    url = defaultPathSerializer({ path, url });
  }
  let search = query ? querySerializer(query) : '';
  if (search.startsWith('?')) {
    search = search.substring(1);
  }
  if (search) {
    url += `?${search}`;
  }
  return url;
};

export function getValidRequestBody(options: {
  body?: unknown;
  bodySerializer?: BodySerializer | null;
  serializedBody?: unknown;
}) {
  const hasBody = options.body !== undefined;
  const isSerializedBody = hasBody && options.bodySerializer;

  if (isSerializedBody) {
    if ('serializedBody' in options) {
      const hasSerializedBody =
        options.serializedBody !== undefined && options.serializedBody !== '';

      return hasSerializedBody ? options.serializedBody : null;
    }

    // not all clients implement a serializedBody property (i.e., client-axios)
    // prefer a positive condition to avoid negated condition lint warnings
    return options.body === '' ? null : options.body;
  }

  // plain/text body
  if (hasBody) {
    return options.body;
  }

  // no body was provided
  return undefined;
}
