RULE_DEFAULT_ARTIFACT_TYPES: dict[str, str] = {
    "RV-03": "TAREA",
    "RV-04": "TAREA",
    "RV-05": "DOCUMENTO",
    "RV-06": "DOCUMENTO",
    "RV-09": "CODIGO",
    "RV-10": "DOCUMENTO",
    "has_duplicated_code": "CODIGO",
    "has_high_severity_vulnerabilities": "CODIGO",
    "has_critical_vulnerabilities": "CODIGO",
    "has_open_high_priority_issues": "TAREA",
    "has_code_smells": "CODIGO",
    "has_security_hotspots": "CODIGO",
    "has_uncovered_code": "CODIGO",
    "has_blocking_issues": "TAREA",
    "meets_minimum_test_coverage": "CODIGO",
    "meets_maximum_complexity": "CODIGO",
}

RULE_CONNECTOR_TYPES: dict[str, list[str]] = {
    "RV-01": [],
    "RV-02": ["GESTOR_TAREAS", "REPO_CODIGO"],
    "RV-03": ["GESTOR_TAREAS"],
    "RV-04": ["GESTOR_TAREAS"],
    "RV-05": ["SISTEMA_DOCUMENTAL"],
    "RV-06": ["SISTEMA_DOCUMENTAL"],
    "RV-07": ["GESTOR_TAREAS", "GESTION_CAMBIOS"],
    "RV-08": ["GESTOR_TAREAS", "HERRAMIENTA_PLANIFICACION"],
    "RV-09": ["REPO_CODIGO"],
    "RV-10": ["SISTEMA_DOCUMENTAL"],
    "has_duplicated_code": ["REPO_CODIGO"],
    "has_high_severity_vulnerabilities": ["REPO_CODIGO"],
    "has_critical_vulnerabilities": ["REPO_CODIGO"],
    "has_open_high_priority_issues": ["GESTOR_TAREAS"],
    "has_code_smells": ["REPO_CODIGO"],
    "has_security_hotspots": ["REPO_CODIGO"],
    "has_uncovered_code": ["REPO_CODIGO"],
    "has_blocking_issues": ["GESTOR_TAREAS"],
    "meets_minimum_test_coverage": ["REPO_CODIGO"],
    "meets_maximum_complexity": ["REPO_CODIGO"],
}

RULE_NAMES: dict[str, str] = {
    "RV-01": "Artefactos existentes",
    "RV-02": "Coherencia IDs",
    "RV-03": "Estado de tareas",
    "RV-04": "Estimación esfuerzo",
    "RV-05": "Documentos existentes",
    "RV-06": "Versión documentos",
    "RV-07": "Release planificada",
    "RV-08": "Coherencia planificación",
    "RV-09": "Referencias código",
    "RV-10": "Informe pruebas",
    "has_duplicated_code": "Código duplicado",
    "has_high_severity_vulnerabilities": "Vulnerabilidades de alta severidad",
    "has_critical_vulnerabilities": "Vulnerabilidades críticas",
    "has_open_high_priority_issues": "Issues de alta prioridad abiertos",
    "has_code_smells": "Code smells",
    "has_security_hotspots": "Security hotspots",
    "has_uncovered_code": "Código sin cobertura",
    "has_blocking_issues": "Issues bloqueantes",
    "meets_minimum_test_coverage": "Cobertura mínima de tests",
    "meets_maximum_complexity": "Complejidad máxima",
}
