from uuid import UUID
from application.ports.input.i_export_service import IExportService
from application.ports.output.i_release_repository import IReleaseRepository
from application.ports.output.i_verification_result_repository import IVerificationResultRepository
from application.ports.output.i_project_repository import IProjectRepository
from core.logger import get_logger
import asyncio
import tempfile
import csv
import os
from datetime import datetime, timezone

_log = get_logger(__name__)


def _write_bytes(path: str, content: bytes) -> None:
    with open(path, "wb") as f:
        f.write(content)


def _write_csv(path: str, results: list) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        if results:
            writer = csv.DictWriter(f, fieldnames=results[0].keys())
            writer.writeheader()
            writer.writerows(results)


class ExportService(IExportService):

    def __init__(
        self,
        release_repository: IReleaseRepository,
        verification_repository: IVerificationResultRepository,
        project_repository: IProjectRepository,
    ):
        self._release_repo = release_repository
        self._verification_repo = verification_repository
        self._project_repo = project_repository

    async def export_verification_to_pdf(self, release_id: UUID, result_id: UUID) -> str:
        result = await self._verification_repo.find_by_id(result_id)
        if not result:
            raise ValueError(f"Verificación no encontrada: {result_id}")

        release = await self._release_repo.get_by_id(release_id)

        temp_dir = tempfile.gettempdir()
        pdf_path = os.path.join(temp_dir, f"verification_{result_id}.pdf")

        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors

        doc = SimpleDocTemplate(pdf_path, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
        styles = getSampleStyleSheet()
        story = []

        title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], fontSize=18, spaceAfter=20, alignment=1)
        story.append(Paragraph("Verification Report", title_style))
        story.append(Spacer(1, 0.3 * inch))

        info_data = [
            ["Release ID", str(release_id)],
            ["Release Name", release.name if release else "N/A"],
            ["Release Version", release.version if release else "N/A"],
            ["Verification ID", str(result_id)],
            ["Verdict", result.verdict.value if hasattr(result.verdict, 'value') else str(result.verdict)],
            ["Executed At", result.executed_at.strftime("%Y-%m-%d %H:%M:%S UTC") if result.executed_at else "N/A"],
        ]
        info_table = Table(info_data, colWidths=[2 * inch, 4 * inch])
        info_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 0.3 * inch))

        if result.summary:
            story.append(Paragraph("Summary", styles['Heading2']))
            story.append(Paragraph(result.summary, styles['Normal']))
            story.append(Spacer(1, 0.2 * inch))

        if result.rule_results:
            story.append(Paragraph("Rule Results", styles['Heading2']))
            for rule_result in result.rule_results:
                rule_name = rule_result.get('rule', 'Unknown Rule')
                rule_status = rule_result.get('status', 'unknown')
                rule_message = rule_result.get('message', '')
                story.append(Paragraph(f"<b>{rule_name}</b>: {rule_status} - {rule_message}", styles['Normal']))
            story.append(Spacer(1, 0.2 * inch))

        story.append(Paragraph(f"Generated by SVAES on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))

        doc.build(story)

        _log.info("PDF exported: result_id=%s path=%s", result_id, pdf_path)
        return pdf_path

    async def export_project_results_to_csv(self, project_id: UUID) -> str:
        project = await self._project_repo.get_by_id(project_id)
        if not project:
            raise ValueError(f"Proyecto no encontrado: {project_id}")

        releases = await self._release_repo.list_by_project(project_id)
        results = []
        for release in releases:
            verifications = await self._verification_repo.find_by_release(release.id)
            for ver in verifications:
                results.append({
                    "release_id": str(release.id),
                    "release_name": release.name,
                    "release_version": release.version,
                    "verification_id": str(ver.id),
                    "verdict": ver.verdict,
                    "executed_at": ver.executed_at.isoformat() if ver.executed_at else "",
                })

        temp_dir = tempfile.gettempdir()
        csv_path = os.path.join(temp_dir, f"project_{project_id}_results.csv")

        await asyncio.to_thread(_write_csv, csv_path, results)

        _log.info("CSV exported: project_id=%s path=%s count=%d", project_id, csv_path, len(results))
        return csv_path