"""
Test suite for ``LoginUseCase``.

``LoginUseCase`` is the application service responsible for authenticating users
via email/password credentials and issuing a signed JWT. It is the sole entry
point into the system for non-OAuth sessions.

Testing strategy:
    Tests are strictly unit-level. The three external ports
    (``IUserRepository``, ``IPasswordHasher``, ``ITokenService``) are replaced
    by test doubles (``AsyncMock`` / ``MagicMock``) to isolate use-case logic
    from any infrastructure.

Key invariants verified:
    - Invalid credentials always raise ``ValueError``, regardless of whether the
      error originates from the email or the password (defence against user
      enumeration).
    - The JWT is **never** issued if authentication fails.
    - On valid credentials, the token is the value returned by
      ``ITokenService.create_access_token`` with the correct arguments.
"""

import uuid
import pytest
from unittest.mock import AsyncMock, MagicMock

from application.use_cases.auth_use_cases import LoginUseCase, LoginCommand
from domain.entities.user import User
from domain.entities.enums import UserRole


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def sample_user():
    """``User`` instance with OPERATOR role used as the base user in tests."""
    return User(
        id=uuid.uuid4(),
        email="operator@example.com",
        hashed_password="$2b$12$hashedpassword",
        role=UserRole.OPERATOR,
        organization_id=uuid.uuid4(),
    )


@pytest.fixture
def user_repo(sample_user):
    """Repository stub that returns ``sample_user`` for any email queried."""
    repo = AsyncMock()
    repo.get_by_email.return_value = sample_user
    return repo


@pytest.fixture
def password_hasher():
    """Hasher stub configured to verify passwords correctly (returns ``True``)."""
    hasher = MagicMock()
    hasher.verify.return_value = True
    return hasher


@pytest.fixture
def token_service():
    """Token service stub that returns a predictable test JWT."""
    svc = MagicMock()
    svc.create_access_token.return_value = "jwt_token_abc"
    return svc


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestLoginUseCase:
    """
    Unit tests for ``LoginUseCase``.

    Covers the complete authentication flow: happy path, unknown user,
    wrong password, and the guarantee that no token is issued on failure.
    All external collaborators are isolated via test doubles.
    """

    async def test_valid_credentials_return_token(
        self, user_repo, password_hasher, token_service, sample_user
    ):
        """
        Valid credentials produce the JWT generated by ``ITokenService``.

        Given:  An existing user in the repository and a hasher that validates the password.
        When:   ``LoginUseCase`` is executed with the correct email and password.
        Then:   The JWT is returned and ``create_access_token`` is called exactly once
                with the authenticated user's ``user_id`` and ``role``.
        """
        use_case = LoginUseCase(user_repo, password_hasher, token_service)
        token = await use_case.execute(
            LoginCommand(email=sample_user.email, password_plain="pass123") # NOSONAR
        )

        assert token == "jwt_token_abc"
        token_service.create_access_token.assert_called_once_with(
            user_id=sample_user.id,
            role=sample_user.role.value,
        )

    async def test_user_not_found_raises_value_error(self, password_hasher, token_service):
        """
        An unregistered email raises ``ValueError`` with a generic message.

        Given:  A repository that returns ``None`` for any email.
        When:   Authentication is attempted with a non-existent address.
        Then:   ``ValueError`` is raised, avoiding disclosure of whether the email
                exists in the system (user-enumeration mitigation).
        """
        repo = AsyncMock()
        repo.get_by_email.return_value = None
        use_case = LoginUseCase(repo, password_hasher, token_service)

        with pytest.raises(ValueError, match="Invalid credentials"):
            await use_case.execute(
                LoginCommand(email="nobody@x.com", password_plain="pw") # NOSONAR
            )

    async def test_wrong_password_raises_value_error(self, user_repo, token_service):
        """
        A wrong password for an existing user raises ``ValueError``.

        Given:  A repository that finds the user but a hasher that rejects the password.
        When:   ``LoginUseCase`` is executed with an incorrect password.
        Then:   ``ValueError`` is raised with the same generic message as the
                missing-email case, ensuring indistinguishable responses.
        """
        bad_hasher = MagicMock()
        bad_hasher.verify.return_value = False
        use_case = LoginUseCase(user_repo, bad_hasher, token_service)

        with pytest.raises(ValueError, match="Invalid credentials"):
            await use_case.execute(
                LoginCommand(email="operator@example.com", password_plain="wrong") # NOSONAR
            )

    async def test_token_not_issued_when_user_not_found(self, password_hasher, token_service):
        """
        The token service is not invoked when authentication fails due to a missing user.

        Given:  A repository that does not find the user.
        When:   Login is attempted and the expected exception is caught.
        Then:   ``ITokenService.create_access_token`` is never called, preventing
                any possibility of issuing unauthorised tokens.
        """
        repo = AsyncMock()
        repo.get_by_email.return_value = None
        use_case = LoginUseCase(repo, password_hasher, token_service)

        with pytest.raises(ValueError):
            await use_case.execute(
                LoginCommand(email="x@x.com", password_plain="pw") # NOSONAR
            )

        token_service.create_access_token.assert_not_called()
