// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * AdminRoleUpdateRequest
 */
export type AdminRoleUpdateRequest = {
    role: UserRole;
};

/**
 * AdminUserCreateRequest
 */
export type AdminUserCreateRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Password
     */
    password: string;
    role?: UserRole;
};

/**
 * ArtifactCreateRequest
 */
export type ArtifactCreateRequest = {
    artifact_type: ArtifactType;
    /**
     * Connector Instance Id
     */
    connector_instance_id: string;
    /**
     * Connector Implementation
     */
    connector_implementation: string;
    /**
     * External Ref
     */
    external_ref: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ArtifactType
 */
export type ArtifactType = 'TAREA' | 'CODIGO' | 'DOCUMENTO';

/**
 * ConnectorCreateRequest
 */
export type ConnectorCreateRequest = {
    /**
     * Connector Type
     */
    connector_type: string;
    /**
     * Connector Implementation
     */
    connector_implementation: string;
    /**
     * Name
     */
    name: string;
    /**
     * Credentials
     *
     * Credenciales y configuración del conector
     */
    credentials: {
        [key: string]: unknown;
    };
};

/**
 * ConnectorUpdateRequest
 */
export type ConnectorUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * CreateAPIKeyRequest
 */
export type CreateApiKeyRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Expires In Days
     */
    expires_in_days?: number | null;
};

/**
 * CustomRoleCreateRequest
 */
export type CustomRoleCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Permissions
     */
    permissions: Array<string>;
};

/**
 * CustomRoleUpdateRequest
 */
export type CustomRoleUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Permissions
     */
    permissions?: Array<string> | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * DeleteAccountRequest
 */
export type DeleteAccountRequest = {
    /**
     * Password
     *
     * Contraseña actual para confirmar la eliminación
     */
    password: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImportArtifactsRequest
 */
export type ImportArtifactsRequest = {
    /**
     * Artifacts
     */
    artifacts: Array<ArtifactCreateRequest>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * NotificationChannelConfig
 */
export type NotificationChannelConfig = {
    /**
     * Channel Type
     *
     * EMAIL, SLACK, MS_TEAMS
     */
    channel_type: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Config Data
     *
     * Channel-specific configuration
     */
    config_data?: {
        [key: string]: unknown;
    };
};

/**
 * OrganizationCreateRequest
 */
export type OrganizationCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Plan
     */
    plan?: string;
};

/**
 * PasswordChangeRequest
 */
export type PasswordChangeRequest = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
    /**
     * Confirm Password
     */
    confirm_password: string;
};

/**
 * ProfileCreateRequest
 */
export type ProfileCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * ProfileUpdateRequest
 */
export type ProfileUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean | null;
};

/**
 * ProjectCreateRequest
 */
export type ProjectCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Profile Id
     */
    profile_id: string;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Accept Terms
     */
    accept_terms: boolean;
    /**
     * Accept Privacy Policy
     */
    accept_privacy_policy: boolean;
};

/**
 * ReleaseCreateRequest
 */
export type ReleaseCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Profile Id
     */
    profile_id?: string | null;
};

/**
 * ReleaseStatus
 */
export type ReleaseStatus = 'BORRADOR' | 'PENDIENTE' | 'EN_VERIFICACION' | 'VALIDA' | 'CON_ADVERTENCIAS' | 'NO_VALIDA' | 'ARCHIVADA';

/**
 * ReleaseUpdateRequest
 */
export type ReleaseUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Version
     */
    version?: string | null;
    /**
     * Description
     */
    description?: string | null;
    status?: ReleaseStatus | null;
};

/**
 * RuleCreateRequest
 */
export type RuleCreateRequest = {
    /**
     * Rule Template
     */
    rule_template: string;
    severity?: SeverityType;
    /**
     * Connector Instance Id
     */
    connector_instance_id?: string | null;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    };
    /**
     * Display Order
     */
    display_order?: number;
};

/**
 * RuleUpdateRequest
 */
export type RuleUpdateRequest = {
    severity?: SeverityType | null;
    /**
     * Connector Instance Id
     */
    connector_instance_id?: string | null;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    } | null;
    /**
     * Display Order
     */
    display_order?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * RulesReloadResponse
 */
export type RulesReloadResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Rules Loaded
     */
    rules_loaded: number;
    /**
     * Message
     */
    message: string;
};

/**
 * SeverityType
 */
export type SeverityType = 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * SubscriptionRequest
 */
export type SubscriptionRequest = {
    /**
     * Event Type
     *
     * RELEASE_VALIDATED, RELEASE_INVALIDATED, RELEASE_PENDING, WEEKLY_DIGEST
     */
    event_type: string;
    /**
     * Enabled
     */
    enabled?: boolean;
};

/**
 * TemplateCloneRequest
 */
export type TemplateCloneRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Target Organization Id
     */
    target_organization_id: string;
};

/**
 * TemplateCreateRequest
 */
export type TemplateCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Profile Id
     */
    profile_id: string;
    /**
     * Project Name Template
     */
    project_name_template?: string | null;
};

/**
 * TemplateUpdateRequest
 */
export type TemplateUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Archived
     */
    is_archived?: boolean | null;
};

/**
 * TransferOwnershipRequest
 */
export type TransferOwnershipRequest = {
    /**
     * New Owner Id
     */
    new_owner_id: string;
};

/**
 * UserInviteRequest
 */
export type UserInviteRequest = {
    /**
     * Email
     */
    email: string;
    role?: UserRole;
};

/**
 * UserNotificationPreferences
 */
export type UserNotificationPreferences = {
    /**
     * Release Validated
     */
    release_validated?: boolean;
    /**
     * Release Invalidated
     */
    release_invalidated?: boolean;
    /**
     * Release Pending Reminder
     */
    release_pending_reminder?: boolean;
    /**
     * Weekly Digest
     */
    weekly_digest?: boolean;
};

/**
 * UserRole
 */
export type UserRole = 'VIEWER' | 'OPERATOR' | 'ADMIN' | 'MANAGER';

/**
 * UserRoleUpdateRequest
 */
export type UserRoleUpdateRequest = {
    role: UserRole;
};

/**
 * UserUpdateRequest
 */
export type UserUpdateRequest = {
    /**
     * Display Name
     */
    display_name?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterApiV1AuthRegisterPostData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type RefreshApiV1AuthRefreshPostData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshApiV1AuthRefreshPostError = RefreshApiV1AuthRefreshPostErrors[keyof RefreshApiV1AuthRefreshPostErrors];

export type RefreshApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type ListOrganizationsApiV1OrganizationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/organizations';
};

export type ListOrganizationsApiV1OrganizationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrganizationsApiV1OrganizationsGetError = ListOrganizationsApiV1OrganizationsGetErrors[keyof ListOrganizationsApiV1OrganizationsGetErrors];

export type ListOrganizationsApiV1OrganizationsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateOrganizationApiV1OrganizationsPostData = {
    body: OrganizationCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/organizations';
};

export type CreateOrganizationApiV1OrganizationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrganizationApiV1OrganizationsPostError = CreateOrganizationApiV1OrganizationsPostErrors[keyof CreateOrganizationApiV1OrganizationsPostErrors];

export type CreateOrganizationApiV1OrganizationsPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetOrganizationApiV1OrganizationsOrgIdGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}';
};

export type GetOrganizationApiV1OrganizationsOrgIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrganizationApiV1OrganizationsOrgIdGetError = GetOrganizationApiV1OrganizationsOrgIdGetErrors[keyof GetOrganizationApiV1OrganizationsOrgIdGetErrors];

export type GetOrganizationApiV1OrganizationsOrgIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProjectByIdApiV1ProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type GetProjectByIdApiV1ProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectByIdApiV1ProjectsProjectIdGetError = GetProjectByIdApiV1ProjectsProjectIdGetErrors[keyof GetProjectByIdApiV1ProjectsProjectIdGetErrors];

export type GetProjectByIdApiV1ProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListAccessibleProjectsApiV1ProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/projects';
};

export type ListAccessibleProjectsApiV1ProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAccessibleProjectsApiV1ProjectsGetError = ListAccessibleProjectsApiV1ProjectsGetErrors[keyof ListAccessibleProjectsApiV1ProjectsGetErrors];

export type ListAccessibleProjectsApiV1ProjectsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListOrgProjectsApiV1OrganizationsOrgIdProjectsGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/organizations/{org_id}/projects';
};

export type ListOrgProjectsApiV1OrganizationsOrgIdProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrgProjectsApiV1OrganizationsOrgIdProjectsGetError = ListOrgProjectsApiV1OrganizationsOrgIdProjectsGetErrors[keyof ListOrgProjectsApiV1OrganizationsOrgIdProjectsGetErrors];

export type ListOrgProjectsApiV1OrganizationsOrgIdProjectsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateProjectApiV1OrganizationsOrgIdProjectsPostData = {
    body: ProjectCreateRequest;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/projects';
};

export type CreateProjectApiV1OrganizationsOrgIdProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectApiV1OrganizationsOrgIdProjectsPostError = CreateProjectApiV1OrganizationsOrgIdProjectsPostErrors[keyof CreateProjectApiV1OrganizationsOrgIdProjectsPostErrors];

export type CreateProjectApiV1OrganizationsOrgIdProjectsPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetProjectApiV1OrganizationsOrgIdProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/projects/{project_id}';
};

export type GetProjectApiV1OrganizationsOrgIdProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectApiV1OrganizationsOrgIdProjectsProjectIdGetError = GetProjectApiV1OrganizationsOrgIdProjectsProjectIdGetErrors[keyof GetProjectApiV1OrganizationsOrgIdProjectsProjectIdGetErrors];

export type GetProjectApiV1OrganizationsOrgIdProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ArchiveProjectApiV1OrganizationsOrgIdProjectsProjectIdArchivePostData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/projects/{project_id}/archive';
};

export type ArchiveProjectApiV1OrganizationsOrgIdProjectsProjectIdArchivePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveProjectApiV1OrganizationsOrgIdProjectsProjectIdArchivePostError = ArchiveProjectApiV1OrganizationsOrgIdProjectsProjectIdArchivePostErrors[keyof ArchiveProjectApiV1OrganizationsOrgIdProjectsProjectIdArchivePostErrors];

export type ArchiveProjectApiV1OrganizationsOrgIdProjectsProjectIdArchivePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RestoreOrganizationApiV1OrganizationsOrgIdRestorePostData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/restore';
};

export type RestoreOrganizationApiV1OrganizationsOrgIdRestorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RestoreOrganizationApiV1OrganizationsOrgIdRestorePostError = RestoreOrganizationApiV1OrganizationsOrgIdRestorePostErrors[keyof RestoreOrganizationApiV1OrganizationsOrgIdRestorePostErrors];

export type RestoreOrganizationApiV1OrganizationsOrgIdRestorePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TransferOwnershipApiV1OrganizationsOrgIdTransferOwnershipPostData = {
    body: TransferOwnershipRequest;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/transfer-ownership';
};

export type TransferOwnershipApiV1OrganizationsOrgIdTransferOwnershipPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransferOwnershipApiV1OrganizationsOrgIdTransferOwnershipPostError = TransferOwnershipApiV1OrganizationsOrgIdTransferOwnershipPostErrors[keyof TransferOwnershipApiV1OrganizationsOrgIdTransferOwnershipPostErrors];

export type TransferOwnershipApiV1OrganizationsOrgIdTransferOwnershipPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListReleasesApiV1ProjectsProjectIdReleasesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/releases';
};

export type ListReleasesApiV1ProjectsProjectIdReleasesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListReleasesApiV1ProjectsProjectIdReleasesGetError = ListReleasesApiV1ProjectsProjectIdReleasesGetErrors[keyof ListReleasesApiV1ProjectsProjectIdReleasesGetErrors];

export type ListReleasesApiV1ProjectsProjectIdReleasesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateReleaseApiV1ProjectsProjectIdReleasesPostData = {
    body: ReleaseCreateRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/releases';
};

export type CreateReleaseApiV1ProjectsProjectIdReleasesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateReleaseApiV1ProjectsProjectIdReleasesPostError = CreateReleaseApiV1ProjectsProjectIdReleasesPostErrors[keyof CreateReleaseApiV1ProjectsProjectIdReleasesPostErrors];

export type CreateReleaseApiV1ProjectsProjectIdReleasesPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteReleaseApiV1ReleasesIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}';
};

export type DeleteReleaseApiV1ReleasesIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteReleaseApiV1ReleasesIdDeleteError = DeleteReleaseApiV1ReleasesIdDeleteErrors[keyof DeleteReleaseApiV1ReleasesIdDeleteErrors];

export type DeleteReleaseApiV1ReleasesIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteReleaseApiV1ReleasesIdDeleteResponse = DeleteReleaseApiV1ReleasesIdDeleteResponses[keyof DeleteReleaseApiV1ReleasesIdDeleteResponses];

export type GetReleaseApiV1ReleasesIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}';
};

export type GetReleaseApiV1ReleasesIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReleaseApiV1ReleasesIdGetError = GetReleaseApiV1ReleasesIdGetErrors[keyof GetReleaseApiV1ReleasesIdGetErrors];

export type GetReleaseApiV1ReleasesIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateReleaseApiV1ReleasesIdPatchData = {
    body: ReleaseUpdateRequest;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}';
};

export type UpdateReleaseApiV1ReleasesIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateReleaseApiV1ReleasesIdPatchError = UpdateReleaseApiV1ReleasesIdPatchErrors[keyof UpdateReleaseApiV1ReleasesIdPatchErrors];

export type UpdateReleaseApiV1ReleasesIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ArchiveReleaseApiV1ReleasesIdArchivePostData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}/archive';
};

export type ArchiveReleaseApiV1ReleasesIdArchivePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveReleaseApiV1ReleasesIdArchivePostError = ArchiveReleaseApiV1ReleasesIdArchivePostErrors[keyof ArchiveReleaseApiV1ReleasesIdArchivePostErrors];

export type ArchiveReleaseApiV1ReleasesIdArchivePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RestoreReleaseApiV1ReleasesIdRestorePostData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}/restore';
};

export type RestoreReleaseApiV1ReleasesIdRestorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RestoreReleaseApiV1ReleasesIdRestorePostError = RestoreReleaseApiV1ReleasesIdRestorePostErrors[keyof RestoreReleaseApiV1ReleasesIdRestorePostErrors];

export type RestoreReleaseApiV1ReleasesIdRestorePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListArtifactsApiV1ReleasesIdArtifactsGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}/artifacts';
};

export type ListArtifactsApiV1ReleasesIdArtifactsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListArtifactsApiV1ReleasesIdArtifactsGetError = ListArtifactsApiV1ReleasesIdArtifactsGetErrors[keyof ListArtifactsApiV1ReleasesIdArtifactsGetErrors];

export type ListArtifactsApiV1ReleasesIdArtifactsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddArtifactApiV1ReleasesIdArtifactsPostData = {
    body: ArtifactCreateRequest;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}/artifacts';
};

export type AddArtifactApiV1ReleasesIdArtifactsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddArtifactApiV1ReleasesIdArtifactsPostError = AddArtifactApiV1ReleasesIdArtifactsPostErrors[keyof AddArtifactApiV1ReleasesIdArtifactsPostErrors];

export type AddArtifactApiV1ReleasesIdArtifactsPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type RemoveArtifactApiV1ReleasesIdArtifactsArtifactIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Artifact Id
         */
        artifact_id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}/artifacts/{artifact_id}';
};

export type RemoveArtifactApiV1ReleasesIdArtifactsArtifactIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveArtifactApiV1ReleasesIdArtifactsArtifactIdDeleteError = RemoveArtifactApiV1ReleasesIdArtifactsArtifactIdDeleteErrors[keyof RemoveArtifactApiV1ReleasesIdArtifactsArtifactIdDeleteErrors];

export type RemoveArtifactApiV1ReleasesIdArtifactsArtifactIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveArtifactApiV1ReleasesIdArtifactsArtifactIdDeleteResponse = RemoveArtifactApiV1ReleasesIdArtifactsArtifactIdDeleteResponses[keyof RemoveArtifactApiV1ReleasesIdArtifactsArtifactIdDeleteResponses];

export type VerifyReleaseApiV1ReleasesIdVerifyPostData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}/verify';
};

export type VerifyReleaseApiV1ReleasesIdVerifyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyReleaseApiV1ReleasesIdVerifyPostError = VerifyReleaseApiV1ReleasesIdVerifyPostErrors[keyof VerifyReleaseApiV1ReleasesIdVerifyPostErrors];

export type VerifyReleaseApiV1ReleasesIdVerifyPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type GetResultsApiV1ReleasesIdResultsGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}/results';
};

export type GetResultsApiV1ReleasesIdResultsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResultsApiV1ReleasesIdResultsGetError = GetResultsApiV1ReleasesIdResultsGetErrors[keyof GetResultsApiV1ReleasesIdResultsGetErrors];

export type GetResultsApiV1ReleasesIdResultsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetResultDetailApiV1ReleasesIdResultsRidGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Rid
         */
        rid: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}/results/{rid}';
};

export type GetResultDetailApiV1ReleasesIdResultsRidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResultDetailApiV1ReleasesIdResultsRidGetError = GetResultDetailApiV1ReleasesIdResultsRidGetErrors[keyof GetResultDetailApiV1ReleasesIdResultsRidGetErrors];

export type GetResultDetailApiV1ReleasesIdResultsRidGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVerificationDetailApiV1ReleasesIdVerificationsVerificationIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Verification Id
         */
        verification_id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}/verifications/{verification_id}';
};

export type GetVerificationDetailApiV1ReleasesIdVerificationsVerificationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVerificationDetailApiV1ReleasesIdVerificationsVerificationIdGetError = GetVerificationDetailApiV1ReleasesIdVerificationsVerificationIdGetErrors[keyof GetVerificationDetailApiV1ReleasesIdVerificationsVerificationIdGetErrors];

export type GetVerificationDetailApiV1ReleasesIdVerificationsVerificationIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportVerificationResultPdfApiV1ReleasesIdResultsRidExportGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Rid
         */
        rid: string;
    };
    query?: {
        /**
         * Format
         *
         * Formato de exportación
         */
        format?: 'pdf';
    };
    url: '/api/v1/releases/{id}/results/{rid}/export';
};

export type ExportVerificationResultPdfApiV1ReleasesIdResultsRidExportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportVerificationResultPdfApiV1ReleasesIdResultsRidExportGetError = ExportVerificationResultPdfApiV1ReleasesIdResultsRidExportGetErrors[keyof ExportVerificationResultPdfApiV1ReleasesIdResultsRidExportGetErrors];

export type ExportVerificationResultPdfApiV1ReleasesIdResultsRidExportGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportProjectResultsCsvApiV1ProjectsProjectIdResultsExportGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Format
         *
         * Formato de exportación
         */
        format?: 'csv';
    };
    url: '/api/v1/projects/{project_id}/results/export';
};

export type ExportProjectResultsCsvApiV1ProjectsProjectIdResultsExportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportProjectResultsCsvApiV1ProjectsProjectIdResultsExportGetError = ExportProjectResultsCsvApiV1ProjectsProjectIdResultsExportGetErrors[keyof ExportProjectResultsCsvApiV1ProjectsProjectIdResultsExportGetErrors];

export type ExportProjectResultsCsvApiV1ProjectsProjectIdResultsExportGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImportArtifactsApiV1ReleasesIdArtifactsImportPostData = {
    body: ImportArtifactsRequest;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/releases/{id}/artifacts/import';
};

export type ImportArtifactsApiV1ReleasesIdArtifactsImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportArtifactsApiV1ReleasesIdArtifactsImportPostError = ImportArtifactsApiV1ReleasesIdArtifactsImportPostErrors[keyof ImportArtifactsApiV1ReleasesIdArtifactsImportPostErrors];

export type ImportArtifactsApiV1ReleasesIdArtifactsImportPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ListConnectorTypesApiV1ConnectorsTypesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/connectors/types';
};

export type ListConnectorTypesApiV1ConnectorsTypesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListConnectorsApiV1OrganizationsOrgIdConnectorsGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: {
        /**
         * Active Only
         */
        active_only?: boolean;
    };
    url: '/api/v1/organizations/{org_id}/connectors';
};

export type ListConnectorsApiV1OrganizationsOrgIdConnectorsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConnectorsApiV1OrganizationsOrgIdConnectorsGetError = ListConnectorsApiV1OrganizationsOrgIdConnectorsGetErrors[keyof ListConnectorsApiV1OrganizationsOrgIdConnectorsGetErrors];

export type ListConnectorsApiV1OrganizationsOrgIdConnectorsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterConnectorApiV1OrganizationsOrgIdConnectorsPostData = {
    body: ConnectorCreateRequest;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/connectors';
};

export type RegisterConnectorApiV1OrganizationsOrgIdConnectorsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterConnectorApiV1OrganizationsOrgIdConnectorsPostError = RegisterConnectorApiV1OrganizationsOrgIdConnectorsPostErrors[keyof RegisterConnectorApiV1OrganizationsOrgIdConnectorsPostErrors];

export type RegisterConnectorApiV1OrganizationsOrgIdConnectorsPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdDeleteData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * Connector Id
         */
        connector_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/connectors/{connector_id}';
};

export type DeleteConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdDeleteError = DeleteConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdDeleteErrors[keyof DeleteConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdDeleteErrors];

export type DeleteConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdDeleteResponse = DeleteConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdDeleteResponses[keyof DeleteConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdDeleteResponses];

export type UpdateConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdPatchData = {
    body: ConnectorUpdateRequest;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * Connector Id
         */
        connector_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/connectors/{connector_id}';
};

export type UpdateConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdPatchError = UpdateConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdPatchErrors[keyof UpdateConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdPatchErrors];

export type UpdateConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdTestPostData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * Connector Id
         */
        connector_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/connectors/{connector_id}/test';
};

export type TestConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdTestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdTestPostError = TestConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdTestPostErrors[keyof TestConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdTestPostErrors];

export type TestConnectorApiV1OrganizationsOrgIdConnectorsConnectorIdTestPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListProfilesApiV1OrganizationsOrgIdProfilesGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/organizations/{org_id}/profiles';
};

export type ListProfilesApiV1OrganizationsOrgIdProfilesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProfilesApiV1OrganizationsOrgIdProfilesGetError = ListProfilesApiV1OrganizationsOrgIdProfilesGetErrors[keyof ListProfilesApiV1OrganizationsOrgIdProfilesGetErrors];

export type ListProfilesApiV1OrganizationsOrgIdProfilesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateProfileApiV1OrganizationsOrgIdProfilesPostData = {
    body: ProfileCreateRequest;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/profiles';
};

export type CreateProfileApiV1OrganizationsOrgIdProfilesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProfileApiV1OrganizationsOrgIdProfilesPostError = CreateProfileApiV1OrganizationsOrgIdProfilesPostErrors[keyof CreateProfileApiV1OrganizationsOrgIdProfilesPostErrors];

export type CreateProfileApiV1OrganizationsOrgIdProfilesPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteProfileApiV1ProfilesProfileIdDeleteData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{profile_id}';
};

export type DeleteProfileApiV1ProfilesProfileIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProfileApiV1ProfilesProfileIdDeleteError = DeleteProfileApiV1ProfilesProfileIdDeleteErrors[keyof DeleteProfileApiV1ProfilesProfileIdDeleteErrors];

export type DeleteProfileApiV1ProfilesProfileIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProfileApiV1ProfilesProfileIdDeleteResponse = DeleteProfileApiV1ProfilesProfileIdDeleteResponses[keyof DeleteProfileApiV1ProfilesProfileIdDeleteResponses];

export type UpdateProfileApiV1ProfilesProfileIdPatchData = {
    body: ProfileUpdateRequest;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{profile_id}';
};

export type UpdateProfileApiV1ProfilesProfileIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileApiV1ProfilesProfileIdPatchError = UpdateProfileApiV1ProfilesProfileIdPatchErrors[keyof UpdateProfileApiV1ProfilesProfileIdPatchErrors];

export type UpdateProfileApiV1ProfilesProfileIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddRuleApiV1ProfilesProfileIdRulesPostData = {
    body: RuleCreateRequest;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{profile_id}/rules';
};

export type AddRuleApiV1ProfilesProfileIdRulesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddRuleApiV1ProfilesProfileIdRulesPostError = AddRuleApiV1ProfilesProfileIdRulesPostErrors[keyof AddRuleApiV1ProfilesProfileIdRulesPostErrors];

export type AddRuleApiV1ProfilesProfileIdRulesPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteRuleApiV1RulesRuleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/v1/rules/{rule_id}';
};

export type DeleteRuleApiV1RulesRuleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRuleApiV1RulesRuleIdDeleteError = DeleteRuleApiV1RulesRuleIdDeleteErrors[keyof DeleteRuleApiV1RulesRuleIdDeleteErrors];

export type DeleteRuleApiV1RulesRuleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRuleApiV1RulesRuleIdDeleteResponse = DeleteRuleApiV1RulesRuleIdDeleteResponses[keyof DeleteRuleApiV1RulesRuleIdDeleteResponses];

export type UpdateRuleApiV1RulesRuleIdPatchData = {
    body: RuleUpdateRequest;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/v1/rules/{rule_id}';
};

export type UpdateRuleApiV1RulesRuleIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRuleApiV1RulesRuleIdPatchError = UpdateRuleApiV1RulesRuleIdPatchErrors[keyof UpdateRuleApiV1RulesRuleIdPatchErrors];

export type UpdateRuleApiV1RulesRuleIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTaskStatusApiV1TasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}';
};

export type GetTaskStatusApiV1TasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskStatusApiV1TasksTaskIdGetError = GetTaskStatusApiV1TasksTaskIdGetErrors[keyof GetTaskStatusApiV1TasksTaskIdGetErrors];

export type GetTaskStatusApiV1TasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentUserProfileApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetCurrentUserProfileApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateCurrentUserProfileApiV1UsersMePatchData = {
    body: UserUpdateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateCurrentUserProfileApiV1UsersMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentUserProfileApiV1UsersMePatchError = UpdateCurrentUserProfileApiV1UsersMePatchErrors[keyof UpdateCurrentUserProfileApiV1UsersMePatchErrors];

export type UpdateCurrentUserProfileApiV1UsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChangePasswordApiV1UsersMePasswordPostData = {
    body: PasswordChangeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type ChangePasswordApiV1UsersMePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordApiV1UsersMePasswordPostError = ChangePasswordApiV1UsersMePasswordPostErrors[keyof ChangePasswordApiV1UsersMePasswordPostErrors];

export type ChangePasswordApiV1UsersMePasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteUserAccountApiV1UsersMeAccountDeleteData = {
    body: DeleteAccountRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/account';
};

export type DeleteUserAccountApiV1UsersMeAccountDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserAccountApiV1UsersMeAccountDeleteError = DeleteUserAccountApiV1UsersMeAccountDeleteErrors[keyof DeleteUserAccountApiV1UsersMeAccountDeleteErrors];

export type DeleteUserAccountApiV1UsersMeAccountDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserAccountApiV1UsersMeAccountDeleteResponse = DeleteUserAccountApiV1UsersMeAccountDeleteResponses[keyof DeleteUserAccountApiV1UsersMeAccountDeleteResponses];

export type ExportUserDataApiV1UsersMeExportGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/export';
};

export type ExportUserDataApiV1UsersMeExportGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListOrganizationUsersApiV1OrganizationsOrgIdUsersGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/organizations/{org_id}/users';
};

export type ListOrganizationUsersApiV1OrganizationsOrgIdUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrganizationUsersApiV1OrganizationsOrgIdUsersGetError = ListOrganizationUsersApiV1OrganizationsOrgIdUsersGetErrors[keyof ListOrganizationUsersApiV1OrganizationsOrgIdUsersGetErrors];

export type ListOrganizationUsersApiV1OrganizationsOrgIdUsersGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type InviteUserApiV1OrganizationsOrgIdUsersInvitePostData = {
    body: UserInviteRequest;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/users/invite';
};

export type InviteUserApiV1OrganizationsOrgIdUsersInvitePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InviteUserApiV1OrganizationsOrgIdUsersInvitePostError = InviteUserApiV1OrganizationsOrgIdUsersInvitePostErrors[keyof InviteUserApiV1OrganizationsOrgIdUsersInvitePostErrors];

export type InviteUserApiV1OrganizationsOrgIdUsersInvitePostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type UpdateUserRoleApiV1OrganizationsOrgIdUsersUserIdRolePatchData = {
    body: UserRoleUpdateRequest;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/users/{user_id}/role';
};

export type UpdateUserRoleApiV1OrganizationsOrgIdUsersUserIdRolePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserRoleApiV1OrganizationsOrgIdUsersUserIdRolePatchError = UpdateUserRoleApiV1OrganizationsOrgIdUsersUserIdRolePatchErrors[keyof UpdateUserRoleApiV1OrganizationsOrgIdUsersUserIdRolePatchErrors];

export type UpdateUserRoleApiV1OrganizationsOrgIdUsersUserIdRolePatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RemoveUserFromOrgApiV1OrganizationsOrgIdUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/users/{user_id}';
};

export type RemoveUserFromOrgApiV1OrganizationsOrgIdUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveUserFromOrgApiV1OrganizationsOrgIdUsersUserIdDeleteError = RemoveUserFromOrgApiV1OrganizationsOrgIdUsersUserIdDeleteErrors[keyof RemoveUserFromOrgApiV1OrganizationsOrgIdUsersUserIdDeleteErrors];

export type RemoveUserFromOrgApiV1OrganizationsOrgIdUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveUserFromOrgApiV1OrganizationsOrgIdUsersUserIdDeleteResponse = RemoveUserFromOrgApiV1OrganizationsOrgIdUsersUserIdDeleteResponses[keyof RemoveUserFromOrgApiV1OrganizationsOrgIdUsersUserIdDeleteResponses];

export type AdminListUsersApiV1AdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Is Active
         */
        is_active?: boolean | null;
        /**
         * Role
         */
        role?: UserRole | null;
    };
    url: '/api/v1/admin/users';
};

export type AdminListUsersApiV1AdminUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminListUsersApiV1AdminUsersGetError = AdminListUsersApiV1AdminUsersGetErrors[keyof AdminListUsersApiV1AdminUsersGetErrors];

export type AdminListUsersApiV1AdminUsersGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminCreateUserApiV1AdminUsersPostData = {
    body: AdminUserCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/users';
};

export type AdminCreateUserApiV1AdminUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminCreateUserApiV1AdminUsersPostError = AdminCreateUserApiV1AdminUsersPostErrors[keyof AdminCreateUserApiV1AdminUsersPostErrors];

export type AdminCreateUserApiV1AdminUsersPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type AdminActivateUserApiV1AdminUsersUserIdActivatePatchData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/activate';
};

export type AdminActivateUserApiV1AdminUsersUserIdActivatePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminActivateUserApiV1AdminUsersUserIdActivatePatchError = AdminActivateUserApiV1AdminUsersUserIdActivatePatchErrors[keyof AdminActivateUserApiV1AdminUsersUserIdActivatePatchErrors];

export type AdminActivateUserApiV1AdminUsersUserIdActivatePatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminDeactivateUserApiV1AdminUsersUserIdDeactivatePatchData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/deactivate';
};

export type AdminDeactivateUserApiV1AdminUsersUserIdDeactivatePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeactivateUserApiV1AdminUsersUserIdDeactivatePatchError = AdminDeactivateUserApiV1AdminUsersUserIdDeactivatePatchErrors[keyof AdminDeactivateUserApiV1AdminUsersUserIdDeactivatePatchErrors];

export type AdminDeactivateUserApiV1AdminUsersUserIdDeactivatePatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminUpdateGlobalRoleApiV1AdminUsersUserIdRolePatchData = {
    body: AdminRoleUpdateRequest;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/role';
};

export type AdminUpdateGlobalRoleApiV1AdminUsersUserIdRolePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateGlobalRoleApiV1AdminUsersUserIdRolePatchError = AdminUpdateGlobalRoleApiV1AdminUsersUserIdRolePatchErrors[keyof AdminUpdateGlobalRoleApiV1AdminUsersUserIdRolePatchErrors];

export type AdminUpdateGlobalRoleApiV1AdminUsersUserIdRolePatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListCustomRolesApiV1OrganizationsOrgIdRolesGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/roles';
};

export type ListCustomRolesApiV1OrganizationsOrgIdRolesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCustomRolesApiV1OrganizationsOrgIdRolesGetError = ListCustomRolesApiV1OrganizationsOrgIdRolesGetErrors[keyof ListCustomRolesApiV1OrganizationsOrgIdRolesGetErrors];

export type ListCustomRolesApiV1OrganizationsOrgIdRolesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateCustomRoleApiV1OrganizationsOrgIdRolesPostData = {
    body: CustomRoleCreateRequest;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/roles';
};

export type CreateCustomRoleApiV1OrganizationsOrgIdRolesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCustomRoleApiV1OrganizationsOrgIdRolesPostError = CreateCustomRoleApiV1OrganizationsOrgIdRolesPostErrors[keyof CreateCustomRoleApiV1OrganizationsOrgIdRolesPostErrors];

export type CreateCustomRoleApiV1OrganizationsOrgIdRolesPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteCustomRoleApiV1RolesRoleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}';
};

export type DeleteCustomRoleApiV1RolesRoleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCustomRoleApiV1RolesRoleIdDeleteError = DeleteCustomRoleApiV1RolesRoleIdDeleteErrors[keyof DeleteCustomRoleApiV1RolesRoleIdDeleteErrors];

export type DeleteCustomRoleApiV1RolesRoleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCustomRoleApiV1RolesRoleIdDeleteResponse = DeleteCustomRoleApiV1RolesRoleIdDeleteResponses[keyof DeleteCustomRoleApiV1RolesRoleIdDeleteResponses];

export type UpdateCustomRoleApiV1RolesRoleIdPatchData = {
    body: CustomRoleUpdateRequest;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}';
};

export type UpdateCustomRoleApiV1RolesRoleIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCustomRoleApiV1RolesRoleIdPatchError = UpdateCustomRoleApiV1RolesRoleIdPatchErrors[keyof UpdateCustomRoleApiV1RolesRoleIdPatchErrors];

export type UpdateCustomRoleApiV1RolesRoleIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDashboardMetricsApiV1DashboardMetricsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Org Id
         *
         * Filter by organization ID
         */
        org_id?: string | null;
    };
    url: '/api/v1/dashboard/metrics';
};

export type GetDashboardMetricsApiV1DashboardMetricsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDashboardMetricsApiV1DashboardMetricsGetError = GetDashboardMetricsApiV1DashboardMetricsGetErrors[keyof GetDashboardMetricsApiV1DashboardMetricsGetErrors];

export type GetDashboardMetricsApiV1DashboardMetricsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListApiKeysApiV1UsersUserIdApiKeysGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/api-keys';
};

export type ListApiKeysApiV1UsersUserIdApiKeysGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListApiKeysApiV1UsersUserIdApiKeysGetError = ListApiKeysApiV1UsersUserIdApiKeysGetErrors[keyof ListApiKeysApiV1UsersUserIdApiKeysGetErrors];

export type ListApiKeysApiV1UsersUserIdApiKeysGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateApiKeyApiV1UsersUserIdApiKeysPostData = {
    body: CreateApiKeyRequest;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/api-keys';
};

export type CreateApiKeyApiV1UsersUserIdApiKeysPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiKeyApiV1UsersUserIdApiKeysPostError = CreateApiKeyApiV1UsersUserIdApiKeysPostErrors[keyof CreateApiKeyApiV1UsersUserIdApiKeysPostErrors];

export type CreateApiKeyApiV1UsersUserIdApiKeysPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type RevokeApiKeyApiV1UsersUserIdApiKeysKeyIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/api-keys/{key_id}';
};

export type RevokeApiKeyApiV1UsersUserIdApiKeysKeyIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeApiKeyApiV1UsersUserIdApiKeysKeyIdDeleteError = RevokeApiKeyApiV1UsersUserIdApiKeysKeyIdDeleteErrors[keyof RevokeApiKeyApiV1UsersUserIdApiKeysKeyIdDeleteErrors];

export type RevokeApiKeyApiV1UsersUserIdApiKeysKeyIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeApiKeyApiV1UsersUserIdApiKeysKeyIdDeleteResponse = RevokeApiKeyApiV1UsersUserIdApiKeysKeyIdDeleteResponses[keyof RevokeApiKeyApiV1UsersUserIdApiKeysKeyIdDeleteResponses];

export type ListTemplatesApiV1TemplatesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Include Archived
         */
        include_archived?: boolean;
    };
    url: '/api/v1/templates';
};

export type ListTemplatesApiV1TemplatesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTemplatesApiV1TemplatesGetError = ListTemplatesApiV1TemplatesGetErrors[keyof ListTemplatesApiV1TemplatesGetErrors];

export type ListTemplatesApiV1TemplatesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateTemplateApiV1TemplatesPostData = {
    body: TemplateCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/templates';
};

export type CreateTemplateApiV1TemplatesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTemplateApiV1TemplatesPostError = CreateTemplateApiV1TemplatesPostErrors[keyof CreateTemplateApiV1TemplatesPostErrors];

export type CreateTemplateApiV1TemplatesPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetTemplateApiV1TemplatesTemplateIdGetData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: string;
    };
    query?: never;
    url: '/api/v1/templates/{template_id}';
};

export type GetTemplateApiV1TemplatesTemplateIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTemplateApiV1TemplatesTemplateIdGetError = GetTemplateApiV1TemplatesTemplateIdGetErrors[keyof GetTemplateApiV1TemplatesTemplateIdGetErrors];

export type GetTemplateApiV1TemplatesTemplateIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateTemplateApiV1TemplatesTemplateIdPatchData = {
    body: TemplateUpdateRequest;
    path: {
        /**
         * Template Id
         */
        template_id: string;
    };
    query?: never;
    url: '/api/v1/templates/{template_id}';
};

export type UpdateTemplateApiV1TemplatesTemplateIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTemplateApiV1TemplatesTemplateIdPatchError = UpdateTemplateApiV1TemplatesTemplateIdPatchErrors[keyof UpdateTemplateApiV1TemplatesTemplateIdPatchErrors];

export type UpdateTemplateApiV1TemplatesTemplateIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ArchiveTemplateApiV1TemplatesTemplateIdArchivePostData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: string;
    };
    query?: never;
    url: '/api/v1/templates/{template_id}/archive';
};

export type ArchiveTemplateApiV1TemplatesTemplateIdArchivePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveTemplateApiV1TemplatesTemplateIdArchivePostError = ArchiveTemplateApiV1TemplatesTemplateIdArchivePostErrors[keyof ArchiveTemplateApiV1TemplatesTemplateIdArchivePostErrors];

export type ArchiveTemplateApiV1TemplatesTemplateIdArchivePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CloneTemplateApiV1TemplatesTemplateIdClonePostData = {
    body: TemplateCloneRequest;
    path: {
        /**
         * Template Id
         */
        template_id: string;
    };
    query?: never;
    url: '/api/v1/templates/{template_id}/clone';
};

export type CloneTemplateApiV1TemplatesTemplateIdClonePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloneTemplateApiV1TemplatesTemplateIdClonePostError = CloneTemplateApiV1TemplatesTemplateIdClonePostErrors[keyof CloneTemplateApiV1TemplatesTemplateIdClonePostErrors];

export type CloneTemplateApiV1TemplatesTemplateIdClonePostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type ListNotificationChannelsApiV1NotificationsChannelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/channels';
};

export type ListNotificationChannelsApiV1NotificationsChannelsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ConfigureNotificationChannelApiV1NotificationsChannelsPostData = {
    body: NotificationChannelConfig;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/channels';
};

export type ConfigureNotificationChannelApiV1NotificationsChannelsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfigureNotificationChannelApiV1NotificationsChannelsPostError = ConfigureNotificationChannelApiV1NotificationsChannelsPostErrors[keyof ConfigureNotificationChannelApiV1NotificationsChannelsPostErrors];

export type ConfigureNotificationChannelApiV1NotificationsChannelsPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteNotificationChannelApiV1NotificationsChannelsChannelIdDeleteData = {
    body?: never;
    path: {
        /**
         * Channel Id
         */
        channel_id: string;
    };
    query?: never;
    url: '/api/v1/notifications/channels/{channel_id}';
};

export type DeleteNotificationChannelApiV1NotificationsChannelsChannelIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNotificationChannelApiV1NotificationsChannelsChannelIdDeleteError = DeleteNotificationChannelApiV1NotificationsChannelsChannelIdDeleteErrors[keyof DeleteNotificationChannelApiV1NotificationsChannelsChannelIdDeleteErrors];

export type DeleteNotificationChannelApiV1NotificationsChannelsChannelIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteNotificationChannelApiV1NotificationsChannelsChannelIdDeleteResponse = DeleteNotificationChannelApiV1NotificationsChannelsChannelIdDeleteResponses[keyof DeleteNotificationChannelApiV1NotificationsChannelsChannelIdDeleteResponses];

export type UpdateNotificationChannelApiV1NotificationsChannelsChannelIdPatchData = {
    body: NotificationChannelConfig;
    path: {
        /**
         * Channel Id
         */
        channel_id: string;
    };
    query?: never;
    url: '/api/v1/notifications/channels/{channel_id}';
};

export type UpdateNotificationChannelApiV1NotificationsChannelsChannelIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNotificationChannelApiV1NotificationsChannelsChannelIdPatchError = UpdateNotificationChannelApiV1NotificationsChannelsChannelIdPatchErrors[keyof UpdateNotificationChannelApiV1NotificationsChannelsChannelIdPatchErrors];

export type UpdateNotificationChannelApiV1NotificationsChannelsChannelIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetNotificationPreferencesApiV1NotificationsPreferencesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/preferences';
};

export type GetNotificationPreferencesApiV1NotificationsPreferencesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateNotificationPreferencesApiV1NotificationsPreferencesPatchData = {
    body: UserNotificationPreferences;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/preferences';
};

export type UpdateNotificationPreferencesApiV1NotificationsPreferencesPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNotificationPreferencesApiV1NotificationsPreferencesPatchError = UpdateNotificationPreferencesApiV1NotificationsPreferencesPatchErrors[keyof UpdateNotificationPreferencesApiV1NotificationsPreferencesPatchErrors];

export type UpdateNotificationPreferencesApiV1NotificationsPreferencesPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubscribeToEventApiV1NotificationsSubscriptionsPostData = {
    body: SubscriptionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/subscriptions';
};

export type SubscribeToEventApiV1NotificationsSubscriptionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscribeToEventApiV1NotificationsSubscriptionsPostError = SubscribeToEventApiV1NotificationsSubscriptionsPostErrors[keyof SubscribeToEventApiV1NotificationsSubscriptionsPostErrors];

export type SubscribeToEventApiV1NotificationsSubscriptionsPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type UnsubscribeFromEventApiV1NotificationsSubscriptionsEventTypeDeleteData = {
    body?: never;
    path: {
        /**
         * Event Type
         */
        event_type: string;
    };
    query?: never;
    url: '/api/v1/notifications/subscriptions/{event_type}';
};

export type UnsubscribeFromEventApiV1NotificationsSubscriptionsEventTypeDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnsubscribeFromEventApiV1NotificationsSubscriptionsEventTypeDeleteError = UnsubscribeFromEventApiV1NotificationsSubscriptionsEventTypeDeleteErrors[keyof UnsubscribeFromEventApiV1NotificationsSubscriptionsEventTypeDeleteErrors];

export type UnsubscribeFromEventApiV1NotificationsSubscriptionsEventTypeDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UnsubscribeFromEventApiV1NotificationsSubscriptionsEventTypeDeleteResponse = UnsubscribeFromEventApiV1NotificationsSubscriptionsEventTypeDeleteResponses[keyof UnsubscribeFromEventApiV1NotificationsSubscriptionsEventTypeDeleteResponses];

export type ReloadCustomRulesApiV1AdminRulesReloadPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/rules/reload';
};

export type ReloadCustomRulesApiV1AdminRulesReloadPostResponses = {
    /**
     * Successful Response
     */
    200: RulesReloadResponse;
};

export type ReloadCustomRulesApiV1AdminRulesReloadPostResponse = ReloadCustomRulesApiV1AdminRulesReloadPostResponses[keyof ReloadCustomRulesApiV1AdminRulesReloadPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
